export const BLOCKED_DOMAINS = [
  'trovaprezzi.it',
  'idealo.it',
  'kelkoo.it',
  'google.com',
  'shopping.google.com',
  'pagomeno.it',
  'bestshopping.com',
  'shoppydoo.it',
  'ciao.it',
  'comparaprezzi.it',
  'prezzo.org',
  'prezzoforte.it',
  'shopmania.it',
  'pricehunter.it'
];

export const BLOCKED_SOURCE_TERMS = [
  'trovaprezzi',
  'idealo',
  'kelkoo',
  'google shopping',
  'pagomeno',
  'bestshopping',
  'shoppydoo',
  'comparatore',
  'comparator',
  'comparazione',
  'confronto prezzi',
  'price comparison',
  'aggregatore',
  'aggregator'
];

// Domini usati come filtro positivo nel tool web_search.
// Sono store ufficiali, siti brand o retailer/marketplace diretti: non comparatori prezzo.
export const OFFICIAL_STORE_DOMAINS = [
  'direct.playstation.com',
  'playstation.com',
  'amazon.it',
  'mediaworld.it',
  'unieuro.it',
  'euronics.it',
  'trony.it',
  'expert.it',
  'gamestop.it',
  'comet.it',
  'monclick.it',
  'eprice.it',
  'yeppon.it',
  'ebay.it',
  'apple.com',
  'samsung.com',
  'mi.com',
  'lenovo.com',
  'dell.com',
  'hp.com',
  'asus.com',
  'acer.com',
  'msi.com',
  'nike.com',
  'adidas.it',
  'zalando.it',
  'decathlon.it',
  'leroymerlin.it',
  'ikea.com',
  'bricoman.it',
  'bricoio.it'
];

export const TRUSTED_STORE_HINTS = [
  'store ufficiale del produttore',
  'sito ufficiale del brand',
  'Amazon pagina prodotto diretta',
  'eBay inserzione diretta',
  'MediaWorld',
  'Unieuro',
  'Euronics',
  'Trony',
  'Expert',
  'GameStop',
  'Comet',
  'Monclick',
  'ePRICE',
  'Yeppon',
  'Leroy Merlin',
  'IKEA',
  'Decathlon',
  'Apple Store',
  'Samsung Shop',
  'Lenovo Store',
  'Dell Store',
  'HP Store',
  'store ufficiali e retailer diretti attendibili disponibili in Italia o UE'
];
